version: 2.1

dockerhub_auth: &dockerhub_auth
  auth:
    username: $DOCKERHUB_USER
    password: $DOCKERHUB_PASSWORD

default: &default
  docker:
    - image: cimg/go:1.19
      <<: *dockerhub_auth
    - image: circleci/mysql:8.0
      <<: *dockerhub_auth
      environment:
        MYSQL_DATABASE: pageboy
        MYSQL_USER: pageboy
        MYSQL_PASSWORD: pageboy
        MYSQL_ROOT_PASSWORD: pageboy
    - image: postgres:13.0
      <<: *dockerhub_auth
      environment:
        POSTGRES_DB: pageboy
        POSTGRES_USER: pageboy
        POSTGRES_PASSWORD: pageboy
    - image: mcmoe/mssqldocker:v2019.CU4.0
      <<: *dockerhub_auth
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: hXUeLZvM4p3r2XeBG

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run: make build
  lint:
    <<: *default
    steps:
      - checkout
      - run: make lint
  test:
    <<: *default
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Waiting for PostgresSQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for PostgresSQL && exit 1
      - run:
          name: Waiting for SQLServer to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 1433 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for SQLServer && exit 1
      - run: make test

workflows:
  version: 2
  general:
    jobs:
      - build:
          context: org-global
      - lint:
          context: org-global
      - test:
          context: org-global
